CREATE TABLE cars (
    car_id number(10) NOT NULL,
    car_name varchar2(50) NOT NULL,
    aspiration varchar2(50) NOT NULL,
    num_of_doors varchar2(10) NOT NULL,
    body_style varchar2(20) NOT NULL,
    drive_wheels varchar2(10) NOT NULL,
    engine_location varchar2(10) NOT NULL,
    wheel_base number(10, 2) NOT NULL,
    length number(10, 2) NOT NULL,
    width number(10, 2) NOT NULL,
    height number(10, 2) NOT NULL,
    curb_weight number(10, 2) NfOT NULL,
    engine_type varchar2(10) NOT NULL,
    num_of_cylinders varchar2(10) NOT NULL,
    engine_size INTEGER NOT NULL,
    fuel_system varchar2(10) NOT NULL,
    compression_ratio DATE NOT NULL,
    horsepower number(10) NOT NULL,
    peak_rpm number(10) NOT NULL,
    city_mpg number(10) NOT NULL,
    highway_mpg number(10) NOT NULL,
    price number(10) NOT NULL,
    CONSTRAINT cars_pk PRIMARY KEY (car_id)
);